# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-07-27 00:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='reservation',
        ),
        migrations.AddField(
            model_name='reservation',
            name='room_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='hotel_app.Room'),
            preserve_default=False,
        ),
    ]
