# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-07-31 17:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_app', '0002_auto_20190727_0017'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='expiration_date',
        ),
        migrations.AddField(
            model_name='payment',
            name='expiration_month',
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment',
            name='expiration_year',
            field=models.IntegerField(default=20),
            preserve_default=False,
        ),
    ]
